---
title: "Lab3"
author: "马宇骁"
date: '\today'
header-includes: \usepackage{ctex}
output:
  pdf_document:
    latex_engine: xelatex
  html_document:
    df_print: paged
---

# 习题1
(1)自行模拟 P69 例3-10 并得出书本中的结论
```{r}
overshot<-c(78, -58, 53, -63, 13, -6, -16, -14, 3, -74, 89, -48, -14, 32, 56, -86, -66, 50, 26, 59, -47, -83, 2, -1, 124, -106, 113, -76, -47, -32, 39, -30, 6, -73, 18, 2, -24, 23, -38, 91, -56, -58, 1, 14, -4, 77, -127, 97, 10, -28, -17, 23, -2, 48, -131, 65, -17)

plot(overshot,type = 'l')
## 大致没有看出有非平稳的特征

acf(overshot, type = "partial")

library(ggfortify)
autoplot(acf(overshot,type = "correlation",plot = FALSE))

```
粗略确定为ARMA(2,1)

(2)自行模拟 P69 例3-11 并得出书本中的结论
```{r}
temperature<-c(-0.40, -0.37, -0.43, -0.47, -0.72, -0.54, -0.47, -0.54, -0.39, -0.19, -0.40, -0.44, -0.49, -0.38, -0.41, -0.27, -0.18, -0.38, -0.22, -0.03, -0.09, -0.28, -0.36, -0.49, -0.25, -0.17, -0.45, -0.32, -0.33, -0.32, -0.29, -0.32, 0.25, -0.05, -0.01, -0.26, -0.48, -0.37, -0.20, -0.15, -0.08, -0.14, -0.13, -0.12, -0.10, 0.13, -0.01, 0.06, -0.17, -0.01, 0.09, 0.05, -0.16, 0.05, -0.02, 0.04, 0.17, 0.19, 0.05, 0.15, 0.13, 0.09, 0.04, 0.11, -0.03, 0.03, 0.15, 0.04, -0.02, -0.13, 0.02, 0.07, 0.20, -0.03, -0.07, -0.19, 0.09, 0.11, 0.06, 0.01, 0.08, 0.02, 0.02, -0.27, -0.18, -0.09, -0.02, -0.13, 0.02, 0.03, -0.12, -0.08, 0.17, -0.09, -0.04, -0.24, -0.16, -0.09, 0.12, 0.27, 0.42, 0.02, 0.30, 0.09, 0.05)

plot(temperature,type = 'l')
## 感觉不太平稳，做adf检验具体确定是否平稳

library(tseries)
adf.test(temperature)
## p值为0.07232大于0.05，不能拒绝原假设，即存在单位根，序列不平稳。（此时应该考虑做一阶差分）

dt = diff(temperature)
adf.test(dt)
## 此时平稳

acf(dt, type = "partial")

acf(dt,type = "correlation")

```
粗略估计ARIMA（9,1,1）


# 习题2
```{r}
#从习题1中任选一个数据完成下面的任务
#以第二个（温度）为例：
#（1）绘制样本自相关图，偏相关图
## 见习题1两个的图像。

#（2）检验平稳性，纯随机性
adf.test(dt)
## 数据平稳，下对差分后的数据检验随机性
Box.test(dt,type = "Ljung-Box")
## 数据不是白噪声序列，存在相关性

#（3）模式识别：定阶，参数估计
library(forecast)
auto.arima(temperature, ic = c("aicc", "aic", "bic"), stepwise = TRUE, trace = TRUE, allowdrift = TRUE, lambda = NULL)
## ARIMA(0,1,3)
model <- arima(temperature,order=c(0,1,3))
summary(model)
#（4）残差的自相关检验
res <- model$residuals
for(i in 1:3) print(Box.test(res,type="Ljung-Box",lag=6*i))
## p值都远大于0.05，是白噪声序列。
#（5）预测
forecast(model,h=5)
```